services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:

